theme: minima
title: Welcome to the Hoo Ja Oh's homepage!
author: Hoo Ja Oh
description: feel free to bookmark this to keep an eye on my project updates

show_excerpts: true # set to false to remove excerpts on the homepage
